# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd2c92d666e4c6d0afaaf257e971b3e7a3544349852fac073331f42a61f78a287e188da25f6f915b409db5604dcc00b5f199d53028b5b8a3c500160e1e7aea0

test:
  secret_key_base: cfbcece06cf7491ca1d9ccb12ba7866c5fa1ea4a5b1c745a8dec4d464dc412d1e7ddbf3dedd6a15cbc6645c7069874f7de9ade2acbff18b7aca5350e14eea863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
